---
kind: Service
apiVersion: v1
metadata:
    name: 'qubership-api-linter-service'
    labels:
        name: 'qubership-api-linter-service'
        app.kubernetes.io/name: 'qubership-api-linter-service'
        app.kubernetes.io/part-of: 'qubership-api-linter-service'
        app.kubernetes.io/managed-by: 'helm'
spec:
    ports:
    -   name: web
        port: 8080
        targetPort: 8080
    selector:
        name: 'qubership-api-linter-service'

