package service

import (
	"context"
	"encoding/json"
	"strconv"
	"time"

	"github.com/Netcracker/qubership-api-linter-service/client"
	"github.com/Netcracker/qubership-api-linter-service/view"
	log "github.com/sirupsen/logrus"

	"github.com/AsaiYusuke/jsonpath/v2"
)

type AiOasExecutor interface {
	LintOperationsForDoc(ctx context.Context, operationData string, rulesetData view.AiRuleset) ([]view.ValidationIssue, int64, error) // TODO
	GetLinterVersion() string
}

func NewAiOasExecutor(lLMClient client.LLMClient) AiOasExecutor {
	return &aiOasExecutor{
		llmClient: lLMClient,
	}
}

type aiOasExecutor struct {
	llmClient client.LLMClient
}

func (s *aiOasExecutor) LintOperationsForDoc(ctx context.Context, operationData string, rulesetData view.AiRuleset) ([]view.ValidationIssue, int64, error) {
	start := time.Now()

	issues, err := s.llmClient.LintOasDocument(ctx, operationData, rulesetData.Prompt)
	if err != nil {
		return nil, 0, err
	}

	var src any
	err = json.Unmarshal([]byte(operationData), &src)
	if err != nil {
		return nil, 0, err
	}

	var res []view.ValidationIssue
	for _, iss := range issues {
		jsonPath := "$"
		parentJsonPath := ""

		for i, p := range iss.Path {
			_, errC := strconv.Atoi(p)
			if errC != nil {
				jsonPath += "['" + p + "']"
			} else {
				jsonPath += "[" + p + "]"
			}
			if i == (len(iss.Path) - 2) {
				parentJsonPath = jsonPath
			}
		}

		parsed, err := jsonpath.Parse(jsonPath)
		if err != nil {
			log.Errorf("Failed to parse jsonpath from Ai linter - '%s': %s", jsonPath, err)
			continue
		}
		_, err = parsed(src)
		if err != nil {
			// try parent json path
			parsedParent, errP := jsonpath.Parse(parentJsonPath)
			if errP != nil {
				log.Errorf("Failed to parse parent jsonpath from Ai linter - '%s': %s", parentJsonPath, errP)
				continue
			}
			_, errP = parsedParent(src)
			if errP != nil {
				log.Errorf("incorrect jsonpath generated by Ai linter - '%s': %s. Parent is not working too - '%s' : %s", jsonPath, err, parentJsonPath, errP)
				continue
			}
			// TODO: or add with empty path?
		}

		res = append(res, view.ValidationIssue{
			Path:     iss.Path,
			Code:     iss.Code,
			Severity: iss.Severity,
			Message:  iss.Message,
		})
	}
	calculationTime := time.Since(start)

	return res, calculationTime.Milliseconds(), nil
}

func (s *aiOasExecutor) GetLinterVersion() string {
	return "1.0"
}
